#!/bin/sh

# This creates an zipped executable package for win32.
# This is currently run from the command line after a new
# executable has been deposited into the win32 folder.

if test -a VERSION ; then
	VERSION="$(cat VERSION)"
	if test -a TARGET ; then
		TARGET="$(cat TARGET)"
#-------------------------------------------------------------
		echo "Building win32 zip..."
		
		mkdir -p ${TARGET}_${VERSION}_win32/data
		mkdir -p ${TARGET}_${VERSION}_win32/games

		cp data/* ${TARGET}_${VERSION}_win32/data
		cp games-etc/*.p games-etc/*.txt ${TARGET}_${VERSION}_win32/games

		cp win32/COPYING.sdl ${TARGET}_${VERSION}_win32/COPYING.sdl.txt
		cp win32/sdl.dll win32/${TARGET}.exe ${TARGET}_${VERSION}_win32

		cp icon-zx80-32.png ${TARGET}_${VERSION}_win32/zx80.png
		cp icon-zx81-32.png ${TARGET}_${VERSION}_win32/zx81.png
		cp icon-${TARGET}-32.png ${TARGET}_${VERSION}_win32/${TARGET}.png

		cp README ${TARGET}_${VERSION}_win32/readme.txt
		cp README.win32 ${TARGET}_${VERSION}_win32/readme.win32.txt
		cp ChangeLog ${TARGET}_${VERSION}_win32/ChangeLog.txt
		cp NEWS ${TARGET}_${VERSION}_win32/NEWS.txt
		cp COPYING ${TARGET}_${VERSION}_win32/COPYING.txt
		
		# Now change all \n to \r\n with unix2dos (actually fromdos).
		unix2dos ${TARGET}_${VERSION}_win32/games/*.txt
		unix2dos ${TARGET}_${VERSION}_win32/*.txt

		zip -r ${TARGET}_${VERSION}_win32.zip ${TARGET}_${VERSION}_win32
		
		rm -rf ${TARGET}_${VERSION}_win32
		
		echo "All done."
#-------------------------------------------------------------
	else
		echo "ERROR: File \"TARGET\" not found. This is a text file with the project name inside it."
	fi
else
	echo "ERROR: File \"VERSION\" not found. This is a text file with the version number inside it."
fi
